### ISSUE TITLE
What is the new googleapis.com permission for

### ISSUE THREAD

**Issue by rtpHarry** [jardrake/Lorem-Ipsum-Generator#1]
I have just got a new update from this plugin and it wants a new permission to access and edit data on googleapis.com.

I cannot see any mention of why - could you clarify please? I have client sites under my control and don't want to give away access to this without good reason.

**Comment by jardrake** [comment]
The reason was that I needed to get license information about when people first installed this extension. However, I completely agree with you that it is a very broad permission that could be abused if something malicious happened to the extension. I'm working to release an update to remove the permission request. I'll see if I can't find some other way to get that information. I'll let you know once it's finished. Thanks for reporting this!

**Comment by jardrake** [comment]
This permission request should be removed as of 2.1.4

**Comment by apokryfos** [comment]
Version 2.2.0 still requires this permission

**Comment by jardrake** [comment]
Greetings,

After removing the permission in 2.1.4, it seems that there isn't a way to get this information without requiring a permission for googleapis. I'm sorry everyone and if google ever fragments the permissions so that I can get the user license for the extension with less permission, I will change it.
